name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: List schemes
      run: xcodebuild -list -project Coffeeist.xcodeproj
    
    - name: Build
      run: |
        xcodebuild build -project Coffeeist.xcodeproj -scheme Coffeeist CODE_SIGNING_ALLOWED=NO 